### ISSUE TITLE
Filter by Genbank features

### ISSUE THREAD

**Issue by asumann** [pirovc/genome_updater#74]
Hi @pirovc,

Access to filtered sequences can be done by Entrez queries (i.e ```Viruses[ORGN] NOT (UNVERIFIED[KYWD] OR STANDARD_DRAFT[KYWD] OR VIRUS_LOW_COVERAGE[KYWD] OR VIRUS_AMBIGUITY[KYWD]```). But this remote access to NCBI tools complicates my pipeline. Also, it makes more sense to build a custom database at the very beginning, instead of entering a remote access step in the middle.

Is it possible to download sequences filtered by Genbank features using genome updater?  

Thanks a million!

**Comment by pirovc** [comment]
Hi @asumann, thanks for the suggestion. genome_updater unfortunately cannot filter by genbank features since it only uses the [assembly_summary.txt](https://ftp.ncbi.nlm.nih.gov/genomes/README_assembly_summary.txt) for data selection and it's limited to that. Maybe you can use the [NCBI E-utilities](https://www.ncbi.nlm.nih.gov/books/NBK25500/?report=classic) to get what you want?
